gatherers:
  - matcher_kwargs:
      targets: /mnt/HD-LSDF/Medaka/segmentations/workshop/heartkidney_decropped/{}.tif
      volumes: /mnt/HD-LSDF/Medaka/segmentations/workshop/medaka_decropped/{}.tif
    seed: 42  
  - matcher_kwargs:
      targets: /mnt/HD-LSDF/Medaka/201905_beamtime_medaka_stained/{}/heartkidney_scaled_0.5_8bit_slices.tif
      volumes: /mnt/HD-LSDF/Medaka/201905_beamtime_medaka_stained/{}/scaled_0.5_8bit_slices.tif
    matcher_function: pseudo_target_matcher  
    split_function: null
    names: train
  - matcher_kwargs:
      targets: /mnt/HD-LSDF/Medaka/201912_beamtime_medaka/{}/heartkidney_scaled_0.5_8bit_slices.tif
      volumes: /mnt/HD-LSDF/Medaka/201912_beamtime_medaka/{}/scaled_0.5_8bit_slices.tif
    matcher_function: pseudo_target_matcher  
    split_function: null
    names: train
  - matcher_kwargs:
      targets: /mnt/HD-LSDF/Medaka/202012_beamtime_medaka/{}/heartkidney_scaled_0.5_8bit_slices.tif
      volumes: /mnt/HD-LSDF/Medaka/202012_beamtime_medaka/{}/scaled_0.5_8bit_slices.tif
    matcher_function: pseudo_target_matcher  
    split_function: null
    names: train

datasets:
  - dataset_names: 'default'
    dataset_kwargs:
      mode_3d: False
      use_ram: False
      localised_crop: True
      segmentation_kwargs:
        label_converter: {'0':0, '4':1, '5':2, '6':3, '7':4, '9':5, '10':6}
      
  - dataset_names: 'train'
    aug_name: medium_aug_rot
    dataset_kwargs:
      crop_size: 256
#    Needs to be precomputed and stored
#    filter_function: classifier_filter
#    filter_kwargs:
#      threshold: 0.5  
    dataset_rebalance_function_name: TVSD_dataset_resample
#    Needs to be precomputed and stored
#    dataset_rebalance_kwargs:
#      contains_markup_path: /home/ws/er5241/Repos/training-repo/utilities/segm_contains_markup.json
    dataloader_kwargs:
      batch_size: 64

  - dataset_names: 'valid'
    dataset_kwargs:
      crop_size: 512
    dataloader_kwargs:
      batch_size: 256