defaults:
    - model:
    - checkpoint:
    - dataset:
    - criterion: crossentropy
    - optimizer: adam
    
logger:
    project_name: fish-eye
    experiment_name: null 
callbacks: 
    - {'name': 'iou_callbacks', 'kwargs': {'classes': [1, 2, 3, 4]}}
    - {'name': 'mean_iou_callback'}
    - {'name': 'EarlyStoppingCallback', 'kwargs': {'patience': 25, 'metric_key': 'mean-iou', 'loader_key': 'valid', 'minimize': False}}
training:
    verbose: True
    num_epochs: 100
    logdir: ./logdir
exclude_combinations: []
attempts: null # fake variable for multirun to repeat action several times
hydra:
    run:
        # Output directory for normal runs
        dir: /home/ws/tb0536/logs/waste/${now:%Y-%m-%d_%H-%M-%S}
    sweep:
       # Output directory for sweep runs
       dir: /home/ws/tb0536/logs/waste/${now:%Y-%m-%d_%H-%M-%S}
       # Output sub directory for sweep runs.
       subdir: ${hydra.job.num}_${hydra.job.override_dirname}

