defaults:
    - model:
    - checkpoint:
    - dataset:
    - dataset/gatherers:
    - dataset/datasets:
    - criterion: crossentropy
    - optimizer: adam
    - callbacks:
    
logger:
    project_name: brain-tumor
    experiment_name: null 
training:
    verbose: True
    num_epochs: 100
    logdir: ./logdir
    load_best_on_end: True
    valid_metric: 'iou-1'
    valid_loader: 'valid'
    minimize_valid_metric: False
exclude_combinations: []
attempts: null # fake variable for multirun to repeat action several times
hydra:
    run:
        # Output directory for normal runs
        dir: /home/ws/tb0536/logs/medaka-supervised/${now:%Y-%m-%d_%H-%M-%S}
    sweep:
       # Output directory for sweep runs
       dir: /home/ws/tb0536/logs/medaka-supervised/${now:%Y-%m-%d_%H-%M-%S}
       # Output sub directory for sweep runs.
       subdir: ${hydra.job.num}_${hydra.job.override_dirname}

