defaults:
    - model:
    - checkpoint:
    - dataset:
    - criterion: crossentropy
    - optimizer: adam
    
logger:
    project_name: medaka-simclr
    experiment_name: null 
callbacks: 
    - {'name': 'mean_displacement_callback'}
    # - {'name': 'iou_callbacks', 'kwargs': {'classes': [1, 3, 4, 5, 6]}}
    # - {'name': 'mean_iou_callback'}
    # - {'name': 'EarlyStoppingCallback', 'kwargs': {'patience': 25, 'metric': 'mean-iou', 'minimize': False}}
    # - {'name': 'iou_callbacks', 'kwargs': {'classes': [1, 3, 4, 5, 6]}}
    # - {'name': 'mean_iou_callback'}
    # - {'name': 'EarlyStoppingCallback', 'kwargs': {'patience': 25, 'metric_key': 'mean-iou', 'loader_key': 'valid', 'minimize': False}}
    # - {'name': 'CheckpointCallback', 'kwargs': {'logdir': './logdir/checkpoints', 'loader_key': 'valid', 'metric_key': 'mean-iou', 'minimize': False, 'resume': False, 'load_on_stage_end': 'last', 'save_n_best': 0}}
training:
    verbose: True
    num_epochs: 200
    logdir: ./logdir
exclude_combinations: []
attempts: null # fake variable for multirun to repeat action several times
hydra:
    run:
        # Output directory for normal runs
        dir: /home/ws/tb0536/logs/medaka-supervised/${now:%Y-%m-%d_%H-%M-%S}
    sweep:
       # Output directory for sweep runs
       dir: /home/ws/tb0536/logs/medaka-supervised/${now:%Y-%m-%d_%H-%M-%S}
       # Output sub directory for sweep runs.
       subdir: ${hydra.job.num}_${hydra.job.override_dirname}

