model:
checkpoint:
dataset:
optimizer:
    lr: 3e-4
criterion:
    criterion_name: CrossentropyND
logger:
    project_name: xenopus
    experiment_name: null 
callbacks: 
    - {'name': 'iou_callbacks', 'kwargs': {'classes': [0, 1]}}
    - {'name': 'mean_iou_callback'}
    - {'name': 'EarlyStoppingCallback', 'kwargs': {'patience': 25, 'metric': 'mean-iou', 'minimize': False}}
training:
    verbose: True
    num_epochs: 100
    logdir: ./logdir
exclude_combinations: []
attempts: null # fake variable for multirun to repeat action several times
hydra:
    run:
        # Output directory for normal runs
        dir: /mnt/data/machine-learning/logs/xenopus/${now:%Y-%m-%d_%H-%M-%S}
    sweep:
       # Output directory for sweep runs
       dir: /mnt/data/machine-learning/logs/xenopus/${now:%Y-%m-%d_%H-%M-%S}
       # Output sub directory for sweep runs.
       subdir: ${hydra.job.num}_${hydra.job.override_dirname}

