defaults:
    - model:
    - checkpoint:
    - dataset:

optimizer:
    lr: 3e-4
criterion:
    criterion_name: FocalLoss
runner:
logger:
    project_name: point-vicreg
    experiment_name: null 
callbacks: 
    - {'name': 'iou_callbacks', 'kwargs': {'classes': [0, 1]}}
    - {'name': 'mean_iou_callback'}
    - {'name': 'dice_callbacks', 'kwargs': {'classes': [0, 1]}}
    - {'name': 'mean_dice_callback'}
    - {'name': 'EarlyStoppingCallback', 'kwargs': {'patience': 100, 'metric': 'mean-iou', 'minimize': False}}
training:
    verbose: True
    num_epochs: 50
    logdir: ./logdir
exclude_combinations: []
attempts: null # fake variable for multirun to repeat action several times
sweep_prefix:
hydra:
    run:
        # Output directory for normal runs
        dir: /home/ws/tb0536/logs/covid/${now:%Y-%m-%d_%H-%M-%S}
    sweep:
       # Output directory for sweep runs
       dir: /home/ws/tb0536/logs/covid/${sweep_prefix}_${now:%Y-%m-%d_%H-%M-%S}
       # Output sub directory for sweep runs.
       subdir: ${hydra.job.num}_${hydra.job.override_dirname}

