defaults:
    - model:
    - checkpoint:
    - dataset:
    - dataset/gatherers:
    - dataset/datasets:
    - criterion: crossentropy
    - optimizer: adam
    - callbacks:
    
logger:
    project_name: fish-eye
    experiment_name: null 
training:
    verbose: True
    num_epochs: 5
    logdir: ./logdir
    main_metric: 'mean-iou'
    minimize_metric: False
exclude_combinations: []
attempts: null # fake variable for multirun to repeat action several times
hydra:
    run:
        # Output directory for normal runs
        dir: /home/ws/er5241/logs/medaka-supervised/${now:%Y-%m-%d_%H-%M-%S}
    sweep:
       # Output directory for sweep runs
       dir: /home/ws/er5241/logs/medaka-supervised/${now:%Y-%m-%d_%H-%M-%S}
       # Output sub directory for sweep runs.
       subdir: ${hydra.job.num}_${hydra.job.override_dirname}

