- dataset_names: default
  dataset_kwargs:
    crop_size: 256
    mode_3d: False
    one_volume_kwargs: {'use_ram': True}
    localised_crop: True
  dataloader_kwargs:
    batch_size: 256
    
- dataset_names: 'train'
  aug_name: medium_aug_rot
  dataset_rebalance_function_name: TVSD_dataset_resample
  dataloader_kwargs:
    batch_size: 64

- dataset_names: 'valid'
  dataloader_kwargs:
    batch_size: 256

- dataset_names: 'infer'
  in_loop: False
  dataloader_kwargs:
    batch_size: 256