- dataset_names: 'train'
  aug_name: medium_aug_rot_float_atro_reco
  dataset_function_name: get_atro_denoising_datasets
  dataloader_kwargs:
    batch_size: 64

- dataset_names: 'valid'
  dataset_function_name: get_atro_denoising_datasets
  aug_name: infer_aug_float_atro
  dataloader_kwargs:
    batch_size: 256
