- dataset_names: 'train'
  aug_name: medium_aug_rot_float_atro_reco
  dataset_function_name: get_noisy_paganin_datasets
  dataset_kwargs:
    noisy_paganin_address: '/mnt/data/denoising/paganin_noise_collection.tif'
  dataloader_kwargs:
    batch_size: 64

- dataset_names: 'valid'
  dataset_function_name: get_noisy_paganin_datasets
  aug_name: infer_aug_float_atro
  dataset_kwargs:
    noisy_paganin_address: '/mnt/data/denoising/paganin_noise_collection.tif'
  dataloader_kwargs:
    batch_size: 256
