- dataset_names: 'train'
  aug_name: medium_aug_rot_float_atro_reco
  dataset_function_name: get_n2n_multitarget_denoising_datasets
  dataset_kwargs:
    lazy: True
  dataloader_kwargs:
    batch_size: 64
  
- dataset_names: 'valid'
  dataset_function_name: get_n2n_multitarget_denoising_datasets
  dataset_kwargs:
    lazy: True
  aug_name: infer_aug_float_atro
  dataloader_kwargs:
    batch_size: 256