# @package _group_
data_gatherer_kwargs:
  targets: /mnt/LSDF/users/zharov/COVID19_1110/uniformly_named_masks/{}.tiff
  volumes: /mnt/LSDF/users/zharov/COVID19_1110/studies/prepared/{}.tiff
aug_name: medium_aug_rot
dataset_kwargs:
  crop_size: 512
  mode_3d: False
  one_volume_kwargs: {'use_ram': True}
  localised_crop: True
dataset_rebalance_function_name: TVSD_dataset_resample
dataset_rebalance_kwargs:
  multiple_datasets_mode: default
dataloader_kwargs:
  batch_size: 16
  drop_last: False
