data_gatherer_kwargs:
  targets: /mnt/LSDF/users/zharov/COVID19_1110/uniformly_named_masks/{}.tiff
  volumes: /mnt/LSDF/users/zharov/COVID19_1110/studies/prepared/{}.tiff
aug_name: medium_aug_rot
test_aug: False
dataset_kwargs:
  crop_size: 512
  mode_3d: False
  one_volume_kwargs: {'use_ram': True}
  localised_crop: True
dataset_rebalance_function_name: TVSD_dataset_resample
test_upsample_to: 10_000
dataset_rebalance_kwargs:
  multiple_datasets_mode: first
dataloader_kwargs:
  batch_size: 16
