# @package _group_
data_gatherer_kwargs:
  targets: /mnt/HD-LSDF/Medaka/segmentations/workshop/eyes_to_train/{}.nii
  volumes: /mnt/HD-LSDF/Medaka/segmentations/workshop/proper_images/{}.tif
  # targets: /mnt/data/machine-learning/workshop_markup/workshop_markup/workshop_markup/eyes_to_train/{}.nii
  # volumes: /mnt/data/machine-learning/workshop_markup/workshop_markup/workshop_markup/proper_images/{}.tif
aug_name: medium_aug_rot
dataset_kwargs:
  crop_size: 512
  mode_3d: False
  one_volume_kwargs: {'use_ram': True}
  localised_crop: True
  label_converter: {'0': 0, '1': 1, '2': 1, '3': 0, '4': 0, '5': 3, '6': 3, '7': 4, '8': 4, '9': 5, '10': 5, '11': 6, '12': 6} # legacy conversion, keeped for compatibility
dataset_rebalance_function_name: TVSD_dataset_resample
dataset_rebalance_kwargs:
  multiple_datasets_mode: default
dataloader_kwargs:
  batch_size: 16
  drop_last: False
