# @package _group_
data_gatherer_name: unsupervised_target_matcher
data_gatherer_kwargs:
  volumes: /mnt/LSDF/projects/code-vita/Medaka/2018_11/*/scaled_0.5_8bit_cropped_slices.tif
train_test_split_kwargs:
  volumes_limit: 250
aug_name: medium_aug_rot
dataset_function_name: get_sorting_TVSD_datasets
dataset_kwargs:
  crop_size: 512
  mode_3d: False
  one_volume_kwargs: {'use_ram': True}
sampler_function_name: ChunkedBatchIdSampler
sampler_function_kwargs: 
  batch_size: 32
  # sorted: True
