gatherers:
  - matcher_kwargs:
      targets: /mnt/HD-LSDF/Medaka/segmentations/workshop/eyes_to_train/{}.nii
      volumes: /mnt/HD-LSDF/Medaka/segmentations/workshop/proper_images/{}.tif
    seed: 42

datasets:
  - dataset_names: 'default'
    dataset_kwargs:
      mode_3d: False
      use_ram: True
      localised_crop: True
      segmentation_kwargs:
        label_converter: {0: 0, 1: 1, 2: 1, 3: 0, 4: 0, 5: 3, 6: 3, 7: 4, 8: 4, 9: 5, 10: 5, 11: 6, 12: 6} # legacy conversion, keeped for compatibility

  - dataset_names: 'train'
    aug_name: medium_aug_rot
    dataset_kwargs:
      crop_size: 256
    dataset_rebalance_function_name: TVSD_dataset_resample
    dataloader_kwargs:
      batch_size: 64

  - dataset_names: 'valid'
    dataset_kwargs:
      crop_size: 512
    dataloader_kwargs:
      batch_size: 256
