# @package _group_
data_gatherer_kwargs:
  volumes: /mnt/data/machine-learning/stained_xenopus/images/{}.tif
  targets: /mnt/data/machine-learning/stained_xenopus/masks/{}.tif
aug_name: medium_aug_rot
random_state: 42
dataset_kwargs:
  crop_size: 256
  mode_3d: False
  one_volume_kwargs: {'use_ram': True}
  localised_crop: True
  label_converter: {'0': 0, '255': 1, '1': 1}
dataset_rebalance_function_name: TVSD_dataset_resample
dataloader_kwargs:
  batch_size: 64
